{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configMap.name }}
  namespace: {{ .Values.namespace.name }}  
data:
{{ toYaml .Values.configMap.data | indent 2 }}
{{- end }}