name: "Build Helm Chart Template"

on: 
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  build-helm-package:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Helm Version
        run: |
          echo "::set-output name=helm_chart_version::$(cat Chart.yaml | grep "version:" | awk -F ":" '{print$2}' | sed 's/ //g'))"
          echo $helm_chart_version

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: List Files After Checkout
        run: |
          tar -czvf helm.tgz .

      - uses: actions/upload-artifact@v3
        with:
          name: helm.tgz
          path: helm.tgz
          