name: "Build Helm Chart Template"

on: 
  push:

jobs:
  build-helm-package:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate Helm Version
        run: |
          echo "::set-output name=helm_chart_version::$(cat charts/Chart.yaml | grep "version:" | awk -F ":" '{print$2}' | sed 's/ //g')"
          echo $helm_chart_version

      - name: Generate Helm Package
        run: |
          tar zcvf helm-charts-generic-${helm_chart_version}.tgz -C charts ./

      - uses: actions/upload-artifact@v3
        with:
          name: helm.tgz
          path: helm.tgz
          