name: "Build Helm Chart Template"

on: 
  push:

jobs:
  build-helm-package:
    runs-on: ubuntu-latest
    steps:


      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate Helm Version
        id: generate_helm_version
        run: |
          helm_chart=$(cat charts/Chart.yaml | grep "version:" | awk -F ":" '{print$2}' | sed 's/ //g')
          echo $helm_chart
                    
          echo "::set-output name=helm_chart_version::$(cat charts/Chart.yaml | grep "version:" | awk -F ":" '{print$2}' | sed 's/ //g')"
          echo $helm_chart_version

      - name: Generate Helm Package
        run: |
          echo ${{ steps.generate_helm_version.outputs.helm_chart_version }}
          export helm_chart_version=${{ steps.generate_helm_version.outputs.helm_chart_version }}
          echo $helm_chart_version
          tar zcvf helm-charts-$helm_chart_version.tgz -C charts ./
          ls -l

      - name: Commit
        run: |
          #git config --global user.name 'Your Name'
          #git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated artifact commit"
          git push

      - uses: actions/upload-artifact@v3
        with:
          name: helm-charts-${{ steps.generate_helm_version.outputs.helm_chart_version }}.tgz
          path: helm-charts-${{ steps.generate_helm_version.outputs.helm_chart_version }}.tgz
          